CC = gcc
CFLAGS = -Wall -g

all: Q1 Q4 Q5 Q6 Q7

Q1: Q1.c
	$(CC) $(CFLAGS) Q1.c -o Q1

Q4: Q4.c
	$(CC) $(CFLAGS) Q4.c -o Q4

Q5: Q5.c
	$(CC) $(CFLAGS) Q5.c -o Q5

Q6: Q6.c
	$(CC) $(CFLAGS) Q6.c -o Q6

Q7: Q7.c
	$(CC) $(CFLAGS) Q7.c -o Q7

clean:
	rm -f Q1 Q4 Q5 Q6 Q7

